#platform :ios, '8.0'
#use_frameworks!

pod 'ComponentKit'
pod 'MJExtension'
pod 'MJRefresh'
pod 'CKToolbox'
pod 'AFNetworking'
pod 'Nimbus'
pod 'AsyncDisplayKit'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTActionSheet',
    # Add any other subspecs you want to use in your project
  ]

pod 'RNController', :path => '../node_modules/react-native-controller-bridge'
